using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Lust.Portfolio;

[GenerateTypedNameReferences]
public sealed partial class PortfolioEditor : Control
{
    private sealed record PortfolioField(
        string LocKey,
        Func<HumanoidCharacterProfile, string> Get,
        Action<HumanoidCharacterProfile, string> Set);

    private static readonly PortfolioField[] Fields =
    [
        new("humanoid-profile-editor-portfolio-distinguishing-features",
            p => p.PortfolioDistinguishingFeatures,
            (p, v) => p.PortfolioDistinguishingFeatures = v),
        new("humanoid-profile-editor-portfolio-region",
            p => p.PortfolioRegion,
            (p, v) => p.PortfolioRegion = v),
        new("humanoid-profile-editor-portfolio-planet-or-colony",
            p => p.PortfolioPlanetOrColony,
            (p, v) => p.PortfolioPlanetOrColony = v),
        new("humanoid-profile-editor-portfolio-street-or-block",
            p => p.PortfolioStreetOrBlock,
            (p, v) => p.PortfolioStreetOrBlock = v),
        new("humanoid-profile-editor-portfolio-apartment",
            p => p.PortfolioApartment,
            (p, v) => p.PortfolioApartment = v),
        new("humanoid-profile-editor-portfolio-education",
            p => p.PortfolioEducation,
            (p, v) => p.PortfolioEducation = v),
        new("humanoid-profile-editor-portfolio-work-experience",
            p => p.PortfolioWorkExperience,
            (p, v) => p.PortfolioWorkExperience = v),
        new("humanoid-profile-editor-portfolio-marital-status",
            p => p.PortfolioMaritalStatus,
            (p, v) => p.PortfolioMaritalStatus = v),
        new("humanoid-profile-editor-portfolio-close-relatives",
            p => p.PortfolioCloseRelatives,
            (p, v) => p.PortfolioCloseRelatives = v),
        new("humanoid-profile-editor-portfolio-emergency-contact",
            p => p.PortfolioEmergencyContact,
            (p, v) => p.PortfolioEmergencyContact = v),
        new("humanoid-profile-editor-portfolio-physiological-traits",
            p => p.PortfolioPhysiologicalTraits,
            (p, v) => p.PortfolioPhysiologicalTraits = v),
        new("humanoid-profile-editor-portfolio-psychological-traits",
            p => p.PortfolioPsychologicalTraits,
            (p, v) => p.PortfolioPsychologicalTraits = v),
        new("humanoid-profile-editor-portfolio-arrest-history",
            p => p.PortfolioArrestHistory,
            (p, v) => p.PortfolioArrestHistory = v),
        new("humanoid-profile-editor-portfolio-conviction-history",
            p => p.PortfolioConvictionHistory,
            (p, v) => p.PortfolioConvictionHistory = v),
    ];

    private HumanoidCharacterProfile _profile = new();

    public event Action<HumanoidCharacterProfile>? OnProfileChanged;

    public PortfolioEditor()
    {
        RobustXamlLoader.Load(this);

        AgeUnknownBox.OnPressed += _ => WriteAgeIsUnknown(AgeUnknownBox.Pressed);

        // Поля на 128 и 64 символа остаются однострочными, пишем по Enter и уходу фокуса.
        SubscribeSingle(1, RegionEdit);
        SubscribeSingle(2, PlanetOrColonyEdit);
        SubscribeSingle(3, StreetOrBlockEdit);
        SubscribeSingle(4, ApartmentEdit);
        SubscribeSingle(7, MaritalStatusEdit);

        // Поля на 512 символов многострочные, у TextEdit нет OnTextEntered и OnFocusExit.
        SubscribeMulti(0, DistinguishingFeaturesEdit);
        SubscribeMulti(5, EducationEdit);
        SubscribeMulti(6, WorkExperienceEdit);
        SubscribeMulti(8, CloseRelativesEdit);
        SubscribeMulti(9, EmergencyContactEdit);
        SubscribeMulti(10, PhysiologicalTraitsEdit);
        SubscribeMulti(11, PsychologicalTraitsEdit);
        SubscribeMulti(12, ArrestHistoryEdit);
        SubscribeMulti(13, ConvictionHistoryEdit);
    }

    /// <summary>
    /// Lust-Edit: однострочное поле, пишем по Enter и при уходе фокуса.
    /// </summary>
    private void SubscribeSingle(int index, LineEdit edit)
    {
        edit.OnTextEntered += e => WriteField(index, e.Text);
        edit.OnFocusExit += e => WriteField(index, e.Text);
    }

    /// <summary>
    /// Lust-Edit: многострочное поле, у TextEdit нет OnTextEntered и OnFocusExit,
    /// поэтому пишем при каждом изменении текста.
    /// </summary>
    private void SubscribeMulti(int index, TextEdit edit)
    {
        edit.OnTextChanged += _ => WriteField(index, Rope.Collapse(edit.TextRope));
    }

    private static void WriteMulti(TextEdit edit, string value)
    {
        if (Rope.Collapse(edit.TextRope) == value)
            return;

        edit.TextRope = new Rope.Leaf(value);
    }

    public void SetProfile(HumanoidCharacterProfile profile)
    {
        _profile = profile;

        WriteMulti(DistinguishingFeaturesEdit, Fields[0].Get(profile));
        RegionEdit.Text = Fields[1].Get(profile);
        PlanetOrColonyEdit.Text = Fields[2].Get(profile);
        StreetOrBlockEdit.Text = Fields[3].Get(profile);
        ApartmentEdit.Text = Fields[4].Get(profile);
        WriteMulti(EducationEdit, Fields[5].Get(profile));
        WriteMulti(WorkExperienceEdit, Fields[6].Get(profile));
        MaritalStatusEdit.Text = Fields[7].Get(profile);
        WriteMulti(CloseRelativesEdit, Fields[8].Get(profile));
        WriteMulti(EmergencyContactEdit, Fields[9].Get(profile));
        WriteMulti(PhysiologicalTraitsEdit, Fields[10].Get(profile));
        WriteMulti(PsychologicalTraitsEdit, Fields[11].Get(profile));
        WriteMulti(ArrestHistoryEdit, Fields[12].Get(profile));
        WriteMulti(ConvictionHistoryEdit, Fields[13].Get(profile));

        AgeUnknownBox.Pressed = profile.AgeIsUnknown;
    }

    private void WriteField(int index, string value)
    {
        var next = new HumanoidCharacterProfile(_profile);
        Fields[index].Set(next, value);
        _profile = next;
        OnProfileChanged?.Invoke(_profile);
    }

    private void WriteAgeIsUnknown(bool value)
    {
        var next = new HumanoidCharacterProfile(_profile);
        next.AgeIsUnknown = value;
        _profile = next;
        OnProfileChanged?.Invoke(_profile);
    }
}
