using Content.Shared._Lust.Preferences;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Lust.Portfolio;

[GenerateTypedNameReferences]
public sealed partial class PortfolioEditor : Control
{
    private sealed record PortfolioField(
        string LocKey,
        Func<HumanoidCharacterProfile, string> Get,
        Action<HumanoidCharacterProfile, string> Set);

    private static readonly PortfolioField[] Fields =
    [
        new("humanoid-profile-editor-portfolio-distinguishing-features",
            p => p.Portfolio.DistinguishingFeatures,
            (p, v) => p.Portfolio.DistinguishingFeatures = v),
        new("humanoid-profile-editor-portfolio-region",
            p => p.Portfolio.Region,
            (p, v) => p.Portfolio.Region = v),
        new("humanoid-profile-editor-portfolio-planet-or-colony",
            p => p.Portfolio.PlanetOrColony,
            (p, v) => p.Portfolio.PlanetOrColony = v),
        new("humanoid-profile-editor-portfolio-address",
            p => p.Portfolio.Address,
            (p, v) => p.Portfolio.Address = v),
        new("humanoid-profile-editor-portfolio-education",
            p => p.Portfolio.Education,
            (p, v) => p.Portfolio.Education = v),
        new("humanoid-profile-editor-portfolio-work-experience",
            p => p.Portfolio.WorkExperience,
            (p, v) => p.Portfolio.WorkExperience = v),
        new("humanoid-profile-editor-portfolio-marital-status",
            p => p.Portfolio.MaritalStatus,
            (p, v) => p.Portfolio.MaritalStatus = v),
        new("humanoid-profile-editor-portfolio-close-relatives",
            p => p.Portfolio.CloseRelatives,
            (p, v) => p.Portfolio.CloseRelatives = v),
        new("humanoid-profile-editor-portfolio-emergency-contact",
            p => p.Portfolio.EmergencyContact,
            (p, v) => p.Portfolio.EmergencyContact = v),
        new("humanoid-profile-editor-portfolio-physiological-traits",
            p => p.Portfolio.PhysiologicalTraits,
            (p, v) => p.Portfolio.PhysiologicalTraits = v),
        new("humanoid-profile-editor-portfolio-psychological-traits",
            p => p.Portfolio.PsychologicalTraits,
            (p, v) => p.Portfolio.PsychologicalTraits = v),
        new("humanoid-profile-editor-portfolio-arrest-history",
            p => p.Portfolio.ArrestHistory,
            (p, v) => p.Portfolio.ArrestHistory = v),
        new("humanoid-profile-editor-portfolio-conviction-history",
            p => p.Portfolio.ConvictionHistory,
            (p, v) => p.Portfolio.ConvictionHistory = v),
    ];

    private HumanoidCharacterProfile _profile = new();

    public event Action<HumanoidCharacterProfile>? OnProfileChanged;

    public PortfolioEditor()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        AgeUnknownButton.AddItem(Loc.GetString("humanoid-profile-editor-portfolio-age-unknown-yes"), 1);
        AgeUnknownButton.AddItem(Loc.GetString("humanoid-profile-editor-portfolio-age-unknown-no"), 0);
        AgeUnknownButton.SelectId(0);
        AgeUnknownButton.OnItemSelected += args =>
        {
            AgeUnknownButton.SelectId(args.Id);
            WriteAgeIsUnknown(args.Id == 1);
        };

        foreach (var status in Enum.GetValues<MaritalStatus>())
        {
            MaritalStatusButton.AddItem(
                Loc.GetString($"humanoid-profile-editor-portfolio-marital-{status.ToString().ToLowerInvariant()}-text"),
                (int) status);
        }
        MaritalStatusButton.OnItemSelected += args =>
        {
            MaritalStatusButton.SelectId(args.Id);
            WriteMaritalStatus((MaritalStatus) args.Id);
        };

        // Однострочные поля (128/32 символа), пишем по Enter и уходу фокуса.
        SubscribeSingle(1, RegionEdit);
        SubscribeSingle(2, PlanetOrColonyEdit);
        SubscribeSingle(3, AddressEdit);

        // Многострочные поля (512 символов), у TextEdit нет OnTextEntered и OnFocusExit.
        SubscribeMulti(0, DistinguishingFeaturesEdit);
        SubscribeMulti(4, EducationEdit);
        SubscribeMulti(5, WorkExperienceEdit);
        SubscribeMulti(7, CloseRelativesEdit);
        SubscribeMulti(8, EmergencyContactEdit);
        SubscribeMulti(9, PhysiologicalTraitsEdit);
        SubscribeMulti(10, PsychologicalTraitsEdit);
        SubscribeMulti(11, ArrestHistoryEdit);
        SubscribeMulti(12, ConvictionHistoryEdit);

        DistinguishingFeaturesGen.OnPressed += _ => GenerateDistinguishingFeatures();
        RegionGen.OnPressed += _ => GenerateRegion();
        PlanetOrColonyGen.OnPressed += _ => GeneratePlanetOrColony();
        AddressGen.OnPressed += _ => GenerateAddress();
        EducationGen.OnPressed += _ => GenerateEducation();
        WorkExperienceGen.OnPressed += _ => GenerateWorkExperience();
        CloseRelativesGen.OnPressed += _ => GenerateCloseRelatives();
        EmergencyContactGen.OnPressed += _ => GenerateEmergencyContact();
        PhysiologicalTraitsGen.OnPressed += _ => GeneratePhysiologicalTraits();
        PsychologicalTraitsGen.OnPressed += _ => GeneratePsychologicalTraits();
        ArrestHistoryGen.OnPressed += _ => GenerateArrestHistory();
        ConvictionHistoryGen.OnPressed += _ => GenerateConvictionHistory();
    }

    /// <summary>
    /// однострочное поле, пишем по Enter и при уходе фокуса.
    /// </summary>
    private void SubscribeSingle(int index, LineEdit edit)
    {
        edit.OnTextEntered += e => WriteField(index, e.Text);
        edit.OnFocusExit += e => WriteField(index, e.Text);
    }

    /// <summary>
    ///  многострочное поле, у TextEdit нет OnTextEntered и OnFocusExit,
    /// поэтому пишем при каждом изменении текста.
    /// </summary>
    private void SubscribeMulti(int index, TextEdit edit)
    {
        edit.OnTextChanged += _ => WriteField(index, Rope.Collapse(edit.TextRope));
    }

    private static void WriteMulti(TextEdit edit, string value)
    {
        if (Rope.Collapse(edit.TextRope) == value)
            return;

        edit.TextRope = new Rope.Leaf(value);
    }

    public void SetProfile(HumanoidCharacterProfile profile)
    {
        _profile = profile;

        WriteMulti(DistinguishingFeaturesEdit, Fields[0].Get(profile));
        RegionEdit.Text = Fields[1].Get(profile);
        PlanetOrColonyEdit.Text = Fields[2].Get(profile);
        AddressEdit.Text = Fields[3].Get(profile);
        WriteMulti(EducationEdit, Fields[4].Get(profile));
        WriteMulti(WorkExperienceEdit, Fields[5].Get(profile));
        MaritalStatusButton.SelectId(PickMaritalStatus(profile));
        WriteMulti(CloseRelativesEdit, Fields[7].Get(profile));
        WriteMulti(EmergencyContactEdit, Fields[8].Get(profile));
        WriteMulti(PhysiologicalTraitsEdit, Fields[9].Get(profile));
        WriteMulti(PsychologicalTraitsEdit, Fields[10].Get(profile));
        WriteMulti(ArrestHistoryEdit, Fields[11].Get(profile));
        WriteMulti(ConvictionHistoryEdit, Fields[12].Get(profile));

        AgeUnknownButton.SelectId(profile.AgeIsUnknown ? 1 : 0);
    }

    private void WriteField(int index, string value)
    {
        var next = new HumanoidCharacterProfile(_profile);
        Fields[index].Set(next, value);
        _profile = next;
        OnProfileChanged?.Invoke(_profile);
    }

    private void GenerateDistinguishingFeatures()
    {
        var value = PortfolioGenerator.Generate(PortfolioPoolLust.DistinguishingFeatures, _profile.Species.Id);
        if (string.IsNullOrEmpty(value))
            return;

        WriteField(0, value);
        WriteMulti(DistinguishingFeaturesEdit, value);
    }

    private void GenerateRegion()
    {
        var value = PortfolioGenerator.Generate(PortfolioPoolLust.Region, _profile.Species.Id);
        if (string.IsNullOrEmpty(value))
            return;

        WriteField(1, value);
        RegionEdit.Text = value;
    }

    private void GeneratePlanetOrColony()
    {
        var value = PortfolioGenerator.Generate(PortfolioPoolLust.PlanetOrColony, _profile.Species.Id);
        if (string.IsNullOrEmpty(value))
            return;

        WriteField(2, value);
        PlanetOrColonyEdit.Text = value;
    }

    private void GenerateAddress()
    {
        var value = PortfolioGenerator.Generate(PortfolioPoolLust.Address, _profile.Species.Id);
        if (string.IsNullOrEmpty(value))
            return;

        WriteField(3, value);
        AddressEdit.Text = value;
    }

    private void GenerateEducation()
    {
        var value = PortfolioGenerator.Generate(PortfolioPoolLust.Education, _profile.Species.Id);
        if (string.IsNullOrEmpty(value))
            return;

        WriteField(4, value);
        WriteMulti(EducationEdit, value);
    }

    private void GenerateWorkExperience()
    {
        var value = PortfolioGenerator.Generate(PortfolioPoolLust.WorkExperience, _profile.Species.Id);
        if (string.IsNullOrEmpty(value))
            return;

        WriteField(5, value);
        WriteMulti(WorkExperienceEdit, value);
    }

    private void GenerateCloseRelatives()
    {
        var value = PortfolioGenerator.Generate(PortfolioPoolLust.CloseRelatives, _profile.Species.Id);
        if (string.IsNullOrEmpty(value))
            return;

        WriteField(7, value);
        WriteMulti(CloseRelativesEdit, value);
    }

    private void GenerateEmergencyContact()
    {
        var value = PortfolioGenerator.Generate(PortfolioPoolLust.EmergencyContact, _profile.Species.Id);
        if (string.IsNullOrEmpty(value))
            return;

        WriteField(8, value);
        WriteMulti(EmergencyContactEdit, value);
    }

    private void GeneratePhysiologicalTraits()
    {
        var value = PortfolioGenerator.Generate(PortfolioPoolLust.PhysiologicalTraits, _profile.Species.Id);
        if (string.IsNullOrEmpty(value))
            return;

        WriteField(9, value);
        WriteMulti(PhysiologicalTraitsEdit, value);
    }

    private void GeneratePsychologicalTraits()
    {
        var value = PortfolioGenerator.Generate(PortfolioPoolLust.PsychologicalTraits, _profile.Species.Id);
        if (string.IsNullOrEmpty(value))
            return;

        WriteField(10, value);
        WriteMulti(PsychologicalTraitsEdit, value);
    }

    private void GenerateArrestHistory()
    {
        var value = PortfolioGenerator.Generate(PortfolioPoolLust.ArrestHistory, _profile.Species.Id);
        if (string.IsNullOrEmpty(value))
            return;

        WriteField(11, value);
        WriteMulti(ArrestHistoryEdit, value);
    }

    private void GenerateConvictionHistory()
    {
        var value = PortfolioGenerator.Generate(PortfolioPoolLust.ConvictionHistory, _profile.Species.Id);
        if (string.IsNullOrEmpty(value))
            return;

        WriteField(12, value);
        WriteMulti(ConvictionHistoryEdit, value);
    }

    private void WriteAgeIsUnknown(bool value)
    {
        var next = new HumanoidCharacterProfile(_profile);
        next.AgeIsUnknown = value;
        _profile = next;
        OnProfileChanged?.Invoke(_profile);
    }

    private static int PickMaritalStatus(HumanoidCharacterProfile profile)
    {
        return Enum.TryParse<MaritalStatus>(profile.Portfolio.MaritalStatus, ignoreCase: true, out var status)
            ? (int) status
            : (int) MaritalStatus.Single;
    }

    private void WriteMaritalStatus(MaritalStatus status)
    {
        var next = new HumanoidCharacterProfile(_profile);
        next.Portfolio.MaritalStatus = status.ToString();
        _profile = next;
        OnProfileChanged?.Invoke(_profile);
    }
}
