using Content.Shared._Lust.Preferences;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Lust.Portfolio;

[GenerateTypedNameReferences]
public sealed partial class PortfolioEditor : Control
{
    private sealed record PortfolioField(
        Func<PortfolioProfile, string> Get,
        Action<PortfolioProfile, string> Set);

    private static readonly PortfolioField DistinguishingFeatures =
        new(p => p.DistinguishingFeatures, (p, v) => p.DistinguishingFeatures = v);

    private static readonly PortfolioField Region =
        new(p => p.Region, (p, v) => p.Region = v);

    private static readonly PortfolioField PlanetOrColony =
        new(p => p.PlanetOrColony, (p, v) => p.PlanetOrColony = v);

    private static readonly PortfolioField Address =
        new(p => p.Address, (p, v) => p.Address = v);

    private static readonly PortfolioField Education =
        new(p => p.Education, (p, v) => p.Education = v);

    private static readonly PortfolioField WorkExperience =
        new(p => p.WorkExperience, (p, v) => p.WorkExperience = v);

    private static readonly PortfolioField CloseRelatives =
        new(p => p.CloseRelatives, (p, v) => p.CloseRelatives = v);

    private static readonly PortfolioField EmergencyContact =
        new(p => p.EmergencyContact, (p, v) => p.EmergencyContact = v);

    private static readonly PortfolioField PhysiologicalTraits =
        new(p => p.PhysiologicalTraits, (p, v) => p.PhysiologicalTraits = v);

    private static readonly PortfolioField PsychologicalTraits =
        new(p => p.PsychologicalTraits, (p, v) => p.PsychologicalTraits = v);

    private static readonly PortfolioField ArrestHistory =
        new(p => p.ArrestHistory, (p, v) => p.ArrestHistory = v);

    private static readonly PortfolioField ConvictionHistory =
        new(p => p.ConvictionHistory, (p, v) => p.ConvictionHistory = v);

    private HumanoidCharacterProfile _profile = new();

    public event Action<HumanoidCharacterProfile>? OnProfileChanged;

    public PortfolioEditor()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        AgeUnknownButton.AddItem(Loc.GetString("humanoid-profile-editor-portfolio-age-unknown-yes"), 1);
        AgeUnknownButton.AddItem(Loc.GetString("humanoid-profile-editor-portfolio-age-unknown-no"), 0);
        AgeUnknownButton.SelectId(0);
        AgeUnknownButton.OnItemSelected += args =>
        {
            AgeUnknownButton.SelectId(args.Id);
            WriteAgeIsUnknown(args.Id == 1);
        };

        foreach (var status in Enum.GetValues<MaritalStatus>())
        {
            MaritalStatusButton.AddItem(
                Loc.GetString($"humanoid-profile-editor-portfolio-marital-{status.ToString().ToLowerInvariant()}-text"),
                (int) status);
        }
        MaritalStatusButton.OnItemSelected += args =>
        {
            MaritalStatusButton.SelectId(args.Id);
            WriteMaritalStatus((MaritalStatus) args.Id);
        };

        // Однострочные поля (128/32 символа), пишем по Enter и уходу фокуса.
        SubscribeSingle(Region, RegionEdit);
        SubscribeSingle(PlanetOrColony, PlanetOrColonyEdit);
        SubscribeSingle(Address, AddressEdit);

        // Многострочные поля (512 символов), у TextEdit нет OnTextEntered и OnFocusExit.
        SubscribeMulti(DistinguishingFeatures, DistinguishingFeaturesEdit);
        SubscribeMulti(Education, EducationEdit);
        SubscribeMulti(WorkExperience, WorkExperienceEdit);
        SubscribeMulti(CloseRelatives, CloseRelativesEdit);
        SubscribeMulti(EmergencyContact, EmergencyContactEdit);
        SubscribeMulti(PhysiologicalTraits, PhysiologicalTraitsEdit);
        SubscribeMulti(PsychologicalTraits, PsychologicalTraitsEdit);
        SubscribeMulti(ArrestHistory, ArrestHistoryEdit);
        SubscribeMulti(ConvictionHistory, ConvictionHistoryEdit);

        DistinguishingFeaturesGen.OnPressed += _ => GenerateDistinguishingFeatures();
        RegionGen.OnPressed += _ => GenerateRegion();
        PlanetOrColonyGen.OnPressed += _ => GeneratePlanetOrColony();
        AddressGen.OnPressed += _ => GenerateAddress();
        EducationGen.OnPressed += _ => GenerateEducation();
        WorkExperienceGen.OnPressed += _ => GenerateWorkExperience();
        CloseRelativesGen.OnPressed += _ => GenerateCloseRelatives();
        EmergencyContactGen.OnPressed += _ => GenerateEmergencyContact();
        PhysiologicalTraitsGen.OnPressed += _ => GeneratePhysiologicalTraits();
        PsychologicalTraitsGen.OnPressed += _ => GeneratePsychologicalTraits();
        ArrestHistoryGen.OnPressed += _ => GenerateArrestHistory();
        ConvictionHistoryGen.OnPressed += _ => GenerateConvictionHistory();
    }

    /// <summary>
    /// однострочное поле, пишем по Enter и при уходе фокуса.
    /// </summary>
    private void SubscribeSingle(PortfolioField field, LineEdit edit)
    {
        edit.OnTextEntered += e => WriteField(field, e.Text);
        edit.OnFocusExit += e => WriteField(field, e.Text);
    }

    /// <summary>
    ///  многострочное поле, у TextEdit нет OnTextEntered и OnFocusExit,
    /// поэтому пишем при каждом изменении текста.
    /// </summary>
    private void SubscribeMulti(PortfolioField field, TextEdit edit)
    {
        edit.OnTextChanged += _ => WriteField(field, Rope.Collapse(edit.TextRope));
    }

    private static void WriteMulti(TextEdit edit, string value)
    {
        if (Rope.Collapse(edit.TextRope) == value)
            return;

        edit.TextRope = new Rope.Leaf(value);
    }

    public void SetProfile(HumanoidCharacterProfile profile)
    {
        _profile = profile;

        WriteMulti(DistinguishingFeaturesEdit, DistinguishingFeatures.Get(profile.Portfolio));
        RegionEdit.Text = Region.Get(profile.Portfolio);
        PlanetOrColonyEdit.Text = PlanetOrColony.Get(profile.Portfolio);
        AddressEdit.Text = Address.Get(profile.Portfolio);
        WriteMulti(EducationEdit, Education.Get(profile.Portfolio));
        WriteMulti(WorkExperienceEdit, WorkExperience.Get(profile.Portfolio));
        MaritalStatusButton.SelectId(PickMaritalStatus(profile));
        WriteMulti(CloseRelativesEdit, CloseRelatives.Get(profile.Portfolio));
        WriteMulti(EmergencyContactEdit, EmergencyContact.Get(profile.Portfolio));
        WriteMulti(PhysiologicalTraitsEdit, PhysiologicalTraits.Get(profile.Portfolio));
        WriteMulti(PsychologicalTraitsEdit, PsychologicalTraits.Get(profile.Portfolio));
        WriteMulti(ArrestHistoryEdit, ArrestHistory.Get(profile.Portfolio));
        WriteMulti(ConvictionHistoryEdit, ConvictionHistory.Get(profile.Portfolio));

        AgeUnknownButton.SelectId(profile.AgeIsUnknown ? 1 : 0);
    }

    private void WriteField(PortfolioField field, string value)
    {
        var next = new HumanoidCharacterProfile(_profile);
        field.Set(next.Portfolio, value);
        _profile = next;
        OnProfileChanged?.Invoke(_profile);
    }

    private void GenerateDistinguishingFeatures()
    {
        var value = PortfolioGenerator.Generate(PortfolioPoolLust.DistinguishingFeatures, _profile.Species.Id);
        if (string.IsNullOrEmpty(value))
            return;

        WriteField(DistinguishingFeatures, value);
        WriteMulti(DistinguishingFeaturesEdit, value);
    }

    private void GenerateRegion()
    {
        var value = PortfolioGenerator.Generate(PortfolioPoolLust.Region, _profile.Species.Id);
        if (string.IsNullOrEmpty(value))
            return;

        WriteField(Region, value);
        RegionEdit.Text = value;
    }

    private void GeneratePlanetOrColony()
    {
        var value = PortfolioGenerator.Generate(PortfolioPoolLust.PlanetOrColony, _profile.Species.Id);
        if (string.IsNullOrEmpty(value))
            return;

        WriteField(PlanetOrColony, value);
        PlanetOrColonyEdit.Text = value;
    }

    private void GenerateAddress()
    {
        var value = PortfolioGenerator.Generate(PortfolioPoolLust.Address, _profile.Species.Id);
        if (string.IsNullOrEmpty(value))
            return;

        WriteField(Address, value);
        AddressEdit.Text = value;
    }

    private void GenerateEducation()
    {
        var value = PortfolioGenerator.Generate(PortfolioPoolLust.Education, _profile.Species.Id);
        if (string.IsNullOrEmpty(value))
            return;

        WriteField(Education, value);
        WriteMulti(EducationEdit, value);
    }

    private void GenerateWorkExperience()
    {
        var value = PortfolioGenerator.Generate(PortfolioPoolLust.WorkExperience, _profile.Species.Id);
        if (string.IsNullOrEmpty(value))
            return;

        WriteField(WorkExperience, value);
        WriteMulti(WorkExperienceEdit, value);
    }

    private void GenerateCloseRelatives()
    {
        var value = PortfolioGenerator.Generate(PortfolioPoolLust.CloseRelatives, _profile.Species.Id);
        if (string.IsNullOrEmpty(value))
            return;

        WriteField(CloseRelatives, value);
        WriteMulti(CloseRelativesEdit, value);
    }

    private void GenerateEmergencyContact()
    {
        var value = PortfolioGenerator.Generate(PortfolioPoolLust.EmergencyContact, _profile.Species.Id);
        if (string.IsNullOrEmpty(value))
            return;

        WriteField(EmergencyContact, value);
        WriteMulti(EmergencyContactEdit, value);
    }

    private void GeneratePhysiologicalTraits()
    {
        var value = PortfolioGenerator.Generate(PortfolioPoolLust.PhysiologicalTraits, _profile.Species.Id);
        if (string.IsNullOrEmpty(value))
            return;

        WriteField(PhysiologicalTraits, value);
        WriteMulti(PhysiologicalTraitsEdit, value);
    }

    private void GeneratePsychologicalTraits()
    {
        var value = PortfolioGenerator.Generate(PortfolioPoolLust.PsychologicalTraits, _profile.Species.Id);
        if (string.IsNullOrEmpty(value))
            return;

        WriteField(PsychologicalTraits, value);
        WriteMulti(PsychologicalTraitsEdit, value);
    }

    private void GenerateArrestHistory()
    {
        var value = PortfolioGenerator.Generate(PortfolioPoolLust.ArrestHistory, _profile.Species.Id);
        if (string.IsNullOrEmpty(value))
            return;

        WriteField(ArrestHistory, value);
        WriteMulti(ArrestHistoryEdit, value);
    }

    private void GenerateConvictionHistory()
    {
        var value = PortfolioGenerator.Generate(PortfolioPoolLust.ConvictionHistory, _profile.Species.Id);
        if (string.IsNullOrEmpty(value))
            return;

        WriteField(ConvictionHistory, value);
        WriteMulti(ConvictionHistoryEdit, value);
    }

    private void WriteAgeIsUnknown(bool value)
    {
        var next = new HumanoidCharacterProfile(_profile);
        next.AgeIsUnknown = value;
        _profile = next;
        OnProfileChanged?.Invoke(_profile);
    }

    private static int PickMaritalStatus(HumanoidCharacterProfile profile)
    {
        return Enum.TryParse<MaritalStatus>(profile.Portfolio.MaritalStatus, ignoreCase: true, out var status)
            ? (int) status
            : (int) MaritalStatus.Single;
    }

    private void WriteMaritalStatus(MaritalStatus status)
    {
        var next = new HumanoidCharacterProfile(_profile);
        next.Portfolio.MaritalStatus = status.ToString();
        _profile = next;
        OnProfileChanged?.Invoke(_profile);
    }
}
