using Content.Shared._Lust.MedicalRecords;
using System.Linq;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Enums;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._Lust.MedicalRecords;

[GenerateTypedNameReferences]
public sealed partial class LustMedicalRecordsWindow : DefaultWindow
{
    private readonly IPrototypeManager _prototype;
    private readonly ILocalizationManager _loc;
    private readonly Gender[] _genders = Enum.GetValues<Gender>();
    private readonly List<SpeciesPrototype> _species;

    public Action<uint?>? OnRecordSelected;
    public Action<uint, Gender, string, string, string, string, string, string>? OnSaveRequested;
    public Action<uint>? OnPrintRequested;

    private bool _isPopulating;
    private bool _isFormattingBiometric;
    private uint? _selectedKey;

    public LustMedicalRecordsWindow()
    {
        RobustXamlLoader.Load(this);
        _prototype = IoCManager.Resolve<IPrototypeManager>();
        _loc = IoCManager.Resolve<ILocalizationManager>();

        _species = _prototype.EnumeratePrototypes<SpeciesPrototype>().ToList();
        _species.Sort((a, b) => string.Compare(
            _loc.GetString(a.Name),
            _loc.GetString(b.Name),
            StringComparison.Ordinal));

        for (var i = 0; i < _genders.Length; i++)
        {
            var gender = _genders[i];
            GenderOption.AddItem(_loc.GetString("station-records-gender", ("gender", gender.ToString())), i);
        }

        for (var i = 0; i < _species.Count; i++)
            SpeciesOption.AddItem(_loc.GetString(_species[i].Name), i);

        GenderOption.OnItemSelected += OnOptionSelected;
        SpeciesOption.OnItemSelected += OnOptionSelected;
        PhysiologicalTraits.OnTextChanged += _ => OnEditableFieldChanged();
        PsychologicalTraits.OnTextChanged += _ => OnEditableFieldChanged();
        Notes.OnTextChanged += _ => OnEditableFieldChanged();
        FingerprintValue.OnTextChanged += _ => OnBiometricTextChanged(FingerprintValue, 32);
        DnaValue.OnTextChanged += _ => OnBiometricTextChanged(DnaValue, 16);

        SaveButton.OnPressed += _ => SaveSelectedRecord();
        PrintButton.OnPressed += _ =>
        {
            if (_selectedKey is { } key)
                OnPrintRequested?.Invoke(key);
        };

        var placeholder = new Rope.Leaf(_loc.GetString("humanoid-profile-data-null"));
        PhysiologicalTraits.Placeholder = placeholder;
        PsychologicalTraits.Placeholder = placeholder;
        Notes.Placeholder = placeholder;

        RecordListing.OnItemSelected += args =>
        {
            if (_isPopulating || RecordListing[args.ItemIndex].Metadata is not uint selectedKey)
                return;

            OnRecordSelected?.Invoke(selectedKey);
        };
    }

    public void UpdateState(LustMedicalRecordsUiState state)
    {
        var listing = state.RecordListing;
        AdvancedAccessStatus.Text = Loc.GetString(
            state.CanEditBiometrics
                ? "lust-medical-records-advanced-access-unlocked"
                : "lust-medical-records-advanced-access-locked");
        _selectedKey = state.SelectedKey;

        if (listing is null || listing.Count == 0)
        {
            SaveButton.Disabled = true;
            PrintButton.Disabled = true;
            RecordListingStatus.Text = Loc.GetString("lust-medical-records-empty-state");
            RecordListingStatus.Visible = true;
            RecordListing.Visible = false;
            RecordDetails.Visible = false;
            return;
        }

        RecordListingStatus.Visible = false;
        RecordListing.Visible = true;
        RecordListing.Clear();
        RecordListing.ClearSelected();

        _isPopulating = true;

        foreach (var (key, name) in listing)
        {
            var item = RecordListing.AddItem(name);
            item.Metadata = key;
            item.Selected = key == state.SelectedKey;
        }

        _isPopulating = false;
        RecordListing.SortItemsByText();

        RecordDetails.Visible = state.SelectedKey != null && state.Name != null;
        SaveButton.Disabled = true;
        PrintButton.Disabled = !RecordDetails.Visible;
        FingerprintValue.Editable = state.CanEditBiometrics;
        DnaValue.Editable = state.CanEditBiometrics;

        if (RecordDetails.Visible)
            UpdateRecordDetails(state);
        else
            SaveButton.Disabled = true;
    }

    private void UpdateRecordDetails(LustMedicalRecordsUiState state)
    {
        var missing = Loc.GetString("humanoid-profile-data-null");
        var profile = state.HumanoidProfile;
        var portfolio = profile?.Portfolio;
        var selectedGender = state.Gender is { } gender
            ? Array.IndexOf(_genders, gender)
            : 0;
        var selectedSpecies = _species.FindIndex(species => species.ID == state.Species);

        _isPopulating = true;
        GenderOption.SelectId(selectedGender < 0 ? 0 : selectedGender);
        SpeciesOption.SelectId(selectedSpecies < 0 ? 0 : selectedSpecies);

        NameValue.Text = PrintableField(state.Name, missing);
        AgeValue.Text = state.Age is > 0 && profile?.AgeIsUnknown != true
            ? state.Age.Value.ToString()
            : missing;

        JobTitleValue.Text = PrintableField(state.JobTitle, missing);
        FingerprintValue.Text = state.CanEditBiometrics
            ? state.Fingerprint ?? string.Empty
            : PrintableField(state.Fingerprint, missing);
        DnaValue.Text = state.CanEditBiometrics
            ? state.DNA ?? string.Empty
            : PrintableField(state.DNA, missing);

        CloseRelatives.TextRope = new Rope.Leaf(PrintableField(portfolio?.CloseRelatives, missing));
        EmergencyContact.TextRope = new Rope.Leaf(PrintableField(portfolio?.EmergencyContact, missing));
        PhysiologicalTraits.TextRope = new Rope.Leaf(portfolio?.PhysiologicalTraits ?? string.Empty);
        PsychologicalTraits.TextRope = new Rope.Leaf(portfolio?.PsychologicalTraits ?? string.Empty);
        Notes.TextRope = new Rope.Leaf(state.Notes ?? string.Empty);

        _isPopulating = false;
        SaveButton.Disabled = true;
    }

    private void OnOptionSelected(OptionButton.ItemSelectedEventArgs args)
    {
        args.Button.SelectId(args.Id);
        OnEditableFieldChanged();
    }

    private void OnEditableFieldChanged()
    {
        if (_isPopulating || _selectedKey == null)
            return;

        SaveButton.Disabled = false;
    }

    private void OnBiometricTextChanged(LineEdit input, int maxLength)
    {
        if (_isPopulating || _isFormattingBiometric)
            return;

        var cursorPosition = input.CursorPosition;
        var formatted = SanitizeBiometricCode(input.Text, maxLength);
        if (input.Text != formatted)
        {
            _isFormattingBiometric = true;
            input.Text = formatted;
            input.CursorPosition = Math.Min(cursorPosition, formatted.Length);
            _isFormattingBiometric = false;
        }

        OnEditableFieldChanged();
    }

    private static string SanitizeBiometricCode(string value, int maxLength)
    {
        var result = new System.Text.StringBuilder(Math.Min(value.Length, maxLength));
        foreach (var character in value)
        {
            if (result.Length >= maxLength)
                break;

            if (character is >= 'a' and <= 'z')
                result.Append((char) (character - ('a' - 'A')));
            else if (character is >= 'A' and <= 'Z' or >= '0' and <= '9')
                result.Append(character);
        }

        return result.ToString();
    }

    private void SaveSelectedRecord()
    {
        if (_selectedKey is not { } key
            || GenderOption.SelectedId < 0 || GenderOption.SelectedId >= _genders.Length
            || SpeciesOption.SelectedId < 0 || SpeciesOption.SelectedId >= _species.Count)
            return;

        OnSaveRequested?.Invoke(
            key,
            _genders[GenderOption.SelectedId],
            _species[SpeciesOption.SelectedId].ID,
            Rope.Collapse(PhysiologicalTraits.TextRope),
            Rope.Collapse(PsychologicalTraits.TextRope),
            Rope.Collapse(Notes.TextRope),
            FingerprintValue.Text,
            DnaValue.Text);
    }

    private static string PrintableField(string? value, string missing)
    {
        return string.IsNullOrWhiteSpace(value) ? missing : value;
    }
}
