using Content.Shared._Lust.Preferences;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Lust.CriminalRecords;

[GenerateTypedNameReferences]
public sealed partial class LustCriminalRecordPortfolioControl : Control
{
    public LustCriminalRecordPortfolioControl()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetProfile(HumanoidCharacterProfile? profile)
    {
        var portfolio = profile?.Portfolio;
        var missing = Loc.GetString("humanoid-profile-data-null");

        DistinguishingFeatures.TextRope = new Rope.Leaf(Display(portfolio?.DistinguishingFeatures, missing));

        Region.Text = Display(portfolio?.Region, missing);
        PlanetOrColony.Text = Display(portfolio?.PlanetOrColony, missing);
        Address.Text = Display(portfolio?.Address, missing);

        CloseRelatives.TextRope = new Rope.Leaf(Display(portfolio?.CloseRelatives, missing));

        EmergencyContact.TextRope = new Rope.Leaf(Display(portfolio?.EmergencyContact, missing));

        ArrestHistory.TextRope = new Rope.Leaf(Display(portfolio?.ArrestHistory, missing));
        ConvictionHistory.TextRope = new Rope.Leaf(Display(portfolio?.ConvictionHistory, missing));

        var maritalStatus = Enum.TryParse<MaritalStatus>(
            portfolio?.MaritalStatus,
            true,
            out var status)
            ? Loc.GetString(
                $"humanoid-profile-editor-portfolio-marital-{status.ToString().ToLowerInvariant()}-text")
            : missing;

        MaritalStatus.Text = maritalStatus;
    }

    private static string Display(string? value, string missing)
    {
        return string.IsNullOrWhiteSpace(value) ? missing : value;
    }
}
