using System.Linq;
using Content.Client.Lobby;
using Content.Client.Roles;
using Content.Shared._Lust.Preferences;
using Content.Shared._Sunrise.Helpers;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.Preferences;
using Content.Shared.Roles;
using Content.Shared.StationRecords;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Enums;
using Robust.Shared.Map;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._Lust.StationRecords;

[GenerateTypedNameReferences]
public sealed partial class LustGeneralRecord : BoxContainer
{
    private readonly IEntityManager _entity;
    private readonly IPrototypeManager _prototype;
    private readonly ILocalizationManager _loc;
    private readonly JobSystem _job;
    private readonly LobbyUIController _controller;

    /// <summary>
    /// Вызывается при нажатии Save. Аргументы — собранная из полей запись и её id.
    /// </summary>
    public Action<GeneralStationRecord, uint>? OnSaveButtonPressed;
    /// <summary>
    /// Вызывается при нажатии Print. Аргумент — id записи.
    /// </summary>
    public Action<uint>? OnPrintPressed;
    /// <summary>
    /// Вызывается при нажатии Delete. Аргумент — id записи.
    /// </summary>
    public Action<uint>? OnDeletePressed;

    private EntityUid _previewDummy;
    private readonly HumanoidCharacterProfile? _profile;

    private readonly List<SpeciesPrototype> _allSpecies;
    private readonly List<JobPrototype> _allJobs;
    private readonly Gender[] _allGender;
    private readonly MaritalStatus[] _allMaritalStatus;

    private readonly bool _hasAccess;

    // Копия этого хранится в серверной системе
    private const int MaxAgeLength = 6;

    /// <summary>
    /// Создаёт контрол просмотра и правки станционной записи: заливает поля,
    /// строит превью персонажа, вешает кнопки и права доступа.
    /// </summary>
    /// <param name="record">Запись для отображения.</param>
    /// <param name="id">Id записи в наборе станции, null — запись без кнопок действий.</param>
    public LustGeneralRecord(GeneralStationRecord record,
        bool canDelete,
        bool canRedactSensitiveData,
        bool hasAccess,
        uint? id,
        in IEntityManager entity,
        in IPrototypeManager prototype,
        in ILocalizationManager loc,
        in JobSystem job,
        in LobbyUIController controller)
    {
        RobustXamlLoader.Load(this);

        _entity = entity;
        _prototype = prototype;
        _loc = loc;
        _job = job;
        _controller = controller;

        _profile = record.HumanoidProfile;
        _allSpecies = _prototype.EnumeratePrototypes<SpeciesPrototype>().ToList();
        _allJobs = _prototype.EnumeratePrototypes<JobPrototype>().ToList();
        _allGender = Enum.GetValues<Gender>();

        _allMaritalStatus = Enum.GetValues<MaritalStatus>();

        // Сортировка рас и работ по имени
        _allSpecies.Sort((a, b)
            => string.Compare(_loc.GetString(a.Name), _loc.GetString(b.Name), StringComparison.Ordinal));

        _allJobs.Sort((a, b)
            => string.Compare(a.LocalizedName, b.LocalizedName, StringComparison.Ordinal));

        // Плейсхолдеры для всех полей ввода
        var placeholderNull = _loc.GetString("humanoid-profile-data-null");

        NameEdit.PlaceHolder = placeholderNull;
        Age.PlaceHolder = placeholderNull;
        Fingerprint.PlaceHolder = placeholderNull;
        Dna.PlaceHolder = placeholderNull;
        LustRegion.PlaceHolder = placeholderNull;
        LustPlanetOrColony.PlaceHolder = placeholderNull;
        LustAddress.PlaceHolder = placeholderNull;


        // Многострочные поля (TextEdit)
        var placeholderRope = new Rope.Leaf(placeholderNull);
        LustDistinguishingFeatures.Placeholder = placeholderRope;
        LustEducation.Placeholder = placeholderRope;
        LustWorkExperience.Placeholder = placeholderRope;
        LustCloseRelatives.Placeholder = placeholderRope;
        LustEmergencyContact.Placeholder = placeholderRope;

        Fingerprint.Editable = canRedactSensitiveData && hasAccess;
        Dna.Editable = canRedactSensitiveData && hasAccess;

        if (canDelete && id != null )
        {
            DeleteButton.Visible = true;
            DeleteButton.OnPressed += _ => OnDeletePressed?.Invoke(id.Value);
        }

        if (id != null )
        {
            SaveButton.Visible = true;
            SaveButton.OnPressed += _ =>
            {
                var updatedRecord = BuildUpdatedRecord(record);
                OnSaveButtonPressed?.Invoke(updatedRecord, id.Value);
            };
        }

        if (id != null )
        {
            PrintButton.Visible = true;
            PrintButton.OnPressed += _ => OnPrintPressed?.Invoke(id.Value);
        }

        _hasAccess = hasAccess;

        UpdateEditableInfo(record);
        UpdateHeading(record);
        ReloadPreview(record.JobPrototype);

        MakeDropDownSelectable();
        CheckAccess();
        CheckChanges();
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();

        _entity.DeleteEntity(_previewDummy);
    }

    /// <summary>
    /// Обновляет информацию, которая может быть изменена игроком.
    /// </summary>
    private void UpdateEditableInfo(GeneralStationRecord record)
    {
        NameEdit.Text = record.Name;
        // Возраст -1 и ниже означает отсутствие данных, показываем пустое поле.
        Age.Text = record.Age <= 0 ? string.Empty : record.Age.ToString();

        for (var i = 0; i < _allGender.Length; i++)
        {
            var item = _allGender[i];
            var name = _loc.GetString("station-records-gender", ("gender", item.ToString()));

            Gender.AddItem(name, i);

            if (item == record.Gender)
                Gender.SelectId(i);
        }

        for (var i = 0; i < _allSpecies.Count; i++)
        {
            var item = _allSpecies[i];

            if (item.StationRecordsHidden && item.ID != record.Species)
                continue;

            var name = _loc.GetString(item.Name);
            Species.AddItem(name, i);

            if (item.ID == record.Species)
                Species.SelectId(i);
        }

        for (var i = 0; i < _allJobs.Count; i++)
        {
            var item = _allJobs[i];

            if (item.OverrideConsoleVisibility == false && item.ID != record.JobPrototype)
                continue;

            var name = item.LocalizedName;
            Job.AddItem(name, i);

            if (item.ID == record.JobPrototype)
                Job.SelectId(i);
        }

        Fingerprint.Text = record.Fingerprint ?? _loc.GetString("generic-not-available-shorthand");
        Dna.Text = record.DNA ?? _loc.GetString("generic-not-available-shorthand");

        Personality.Placeholder = new Rope.Leaf(_loc.GetString("station-records-ui-personality-placeholder"));

        if (!string.IsNullOrEmpty(record.Personality))
            Personality.TextRope = new Rope.Leaf(record.Personality);

        var portfolio = record.HumanoidProfile?.Portfolio ?? new PortfolioProfile();

        LustRegion.Text = portfolio.Region;
        LustPlanetOrColony.Text = portfolio.PlanetOrColony;
        LustAddress.Text = portfolio.Address;

        LustDistinguishingFeatures.TextRope = new Rope.Leaf(portfolio.DistinguishingFeatures);
        LustEducation.TextRope = new Rope.Leaf(portfolio.Education);
        LustWorkExperience.TextRope = new Rope.Leaf(portfolio.WorkExperience);
        LustCloseRelatives.TextRope = new Rope.Leaf(portfolio.CloseRelatives);
        LustEmergencyContact.TextRope = new Rope.Leaf(portfolio.EmergencyContact);

        var marital = PickMaritalStatus(portfolio.MaritalStatus);

        for (var i = 0; i < _allMaritalStatus.Length; i++)
        {
            var status = _allMaritalStatus[i];
            LustMaritalStatus.AddItem(
                _loc.GetString($"humanoid-profile-editor-portfolio-marital-{status.ToString().ToLowerInvariant()}-text"),
                i);

            if ((int) status == marital)
                LustMaritalStatus.SelectId(i);
        }
    }

    /// <summary>
    /// Обновляет заголовок сверху персонажа.
    /// </summary>
    private void UpdateHeading(GeneralStationRecord record)
    {
        SubText.Visible = false;
        NameHeading.Text = record.Name;

        if (!_prototype.TryIndex<JobPrototype>(record.JobPrototype, out var job))
            return;

        SubText.Text = $"{job.LocalizedName}";
        SubText.Visible = true;

        if (!_job.TryGetDepartment(job.ID, out var department))
            return;

        SubText.Text = $"{_loc.GetString(department.Name)}, {job.LocalizedName}";
    }

    /// <summary>
    /// Обновляет превью игрока.
    /// </summary>
    private void ReloadPreview(ProtoId<JobPrototype> jobProtoId)
    {
        if (!_prototype.TryIndex(jobProtoId, out var job))
            return;

        _entity.DeleteEntity(_previewDummy);
        _previewDummy = EntityUid.Invalid;

        if (job.JobEntity != null)
            _previewDummy = _entity.Spawn(job.JobEntity, MapCoordinates.Nullspace);

        if (_profile != null && _prototype.HasIndex(_profile.Species))
            _previewDummy = _controller.LoadProfileEntity(_profile, job, true);

        SpriteView.SetEntity(_previewDummy);
    }

    /// <summary>
    /// Собирает обновлённую запись из полей интерфейса для отправки на сервер.
    /// Строки проходят санитизацию, возраст разбирается один раз.
    /// </summary>
    private GeneralStationRecord BuildUpdatedRecord(GeneralStationRecord original)
    {
        var textAge = Age.Text.SanitizeInput(MaxAgeLength);
        var ageEntered = int.TryParse(textAge, out var ageVal); // разбор один раз, дальше переиспользуется

        var maritalStatus = LustMaritalStatus.SelectedId >= 0 && LustMaritalStatus.SelectedId < _allMaritalStatus.Length
            ? _allMaritalStatus[LustMaritalStatus.SelectedId]
            : MaritalStatus.Single;

        var portfolio = new PortfolioProfile(original.HumanoidProfile?.Portfolio ?? new PortfolioProfile())
        {
            Region = LustRegion.Text,
            PlanetOrColony = LustPlanetOrColony.Text,
            Address = LustAddress.Text,
            DistinguishingFeatures = Rope.Collapse(LustDistinguishingFeatures.TextRope),
            Education = Rope.Collapse(LustEducation.TextRope),
            WorkExperience = Rope.Collapse(LustWorkExperience.TextRope),
            MaritalStatus = maritalStatus.ToString(),
            CloseRelatives = Rope.Collapse(LustCloseRelatives.TextRope),
            EmergencyContact = Rope.Collapse(LustEmergencyContact.TextRope),
        };

        var profile = (original.HumanoidProfile ?? new HumanoidCharacterProfile())
            .WithPortfolio(portfolio);

        var updated = original with
        {
            Name = NameEdit.Text,
            Age = ageEntered ? ageVal : original.Age,
            Gender = _allGender[Gender.SelectedId],
            Species = _allSpecies[Species.SelectedId].ID,
            JobPrototype = _allJobs[Job.SelectedId].ID,
            Fingerprint = Fingerprint.Text,
            DNA = Dna.Text,
            Personality = Rope.Collapse(Personality.TextRope),
            HumanoidProfile = profile,
        };

        return GeneralStationRecord.SanitizeRecord(updated, in _prototype);
    }

    private void MakeDropDownSelectable()
    {
        // Почему это не встроено в сами кнопки
        foreach (var child in ControlGrid.Children)
        {
            if (child is not OptionButton optionButton)
                continue;

            optionButton.OnItemSelected += Select;
        }
    }

    private void Select(OptionButton.ItemSelectedEventArgs args)
    {
        args.Button.SelectId(args.Id);
        MakeSaveAvailable();
    }

    private void CheckAccess()
    {
        NameEdit.Editable = _hasAccess;
        Age.Editable = _hasAccess;
        Personality.Editable = _hasAccess;
        Gender.Disabled = !_hasAccess;
        Species.Disabled = !_hasAccess;
        Job.Disabled = !_hasAccess;

        foreach (var child in PortfolioGrid.Children)
        {
            switch (child)
            {
                case LineEdit line:
                    line.Editable = _hasAccess;
                    break;
                case TextEdit text:
                    text.Editable = _hasAccess;
                    break;
            }
        }

        LustMaritalStatus.Disabled = !_hasAccess;
    }

    private void CheckChanges()
    {
        foreach (var child in ControlGrid.Children)
        {
            if (child is not LineEdit lineEdit)
                continue;

            lineEdit.OnTextChanged += _ => MakeSaveAvailable();
        }

        Personality.OnTextChanged += _ => MakeSaveAvailable();

        foreach (var child in PortfolioGrid.Children)
        {
            switch (child)
            {
                case LineEdit line:
                    line.OnTextChanged += _ => MakeSaveAvailable();
                    break;
                case TextEdit text:
                    text.OnTextChanged += _ => MakeSaveAvailable();
                    break;
            }
        }

        LustMaritalStatus.OnItemSelected += Select;
    }

    private void MakeSaveAvailable()
    {
        SaveButton.Disabled = !_hasAccess;
    }

    /// <summary>
    /// строка в портфолио может прийти пустой или с неизвестным значением,
    /// тогда показываем "не в браке".
    /// </summary>
    private static int PickMaritalStatus(string value)
    {
        return Enum.TryParse<MaritalStatus>(value, true, out var status)
            ? (int) status
            : (int) MaritalStatus.Single;
    }
}
